Only remove gms if Denylist is enforced
kdrag0n/safetynet-fix pull request #150
Opened 2022-02-03 02:15 UTC by ipdev99

Originally Magisk required the Denylist to be enforced to access the Denylist.
When enforced, Magisk is unloaded while the processes on the Denylist are called.

Now you can access the Denylist when it is not enforced.
Since Magisk runs normally when not enforced, the Denylist is just a list.

No need to remove 'gms' from the Denylist when it is not enforced.

2022-02-03 02:22 UTC, ipdev99 commented
Just to clearify the command.
`magisk --denylist` returns either.

_Denylist is not enforced_ with a return value of "1"

_Denylist is enforced_ with a return value of "0"

2022-02-09 02:46 UTC, kdrag0n requested changes
This makes sense, but I'm not sure about merging it because it might cause issues for users who add GMS to the DenyList without enforcing it *and* don't have any special modules that use the DenyList.

For example, if someone adds Play Services to the DenyList but doesn't enable "Enforce DenyList" until later, this will miss it and the module won't work for them until they reboot.

2022-02-09 02:46 UTC, kdrag0n commented on magisk/post-fs-data.sh
> +magisk --denylist status 2> /dev/null && magisk --denylist rm com.google.android.gms
I know `&&` works as a shorthand in this case, but please use this construct for clarity:

```bash
if cmd; then
    ...
fi
```

2022-02-13 19:32 UTC, ipdev99 commented
> This makes sense, but I'm not sure about merging it because it might cause issues for users who add GMS to the DenyList without enforcing it _and_ don't have any special modules that use the DenyList.
Since Magisk ignores the DenyList when it is not enforcing, it does not matter what is on the list.
Unless there is a Module that sources the DenyList when not enforcing, nothing will happen with the proccesses on the DenyList when it is not enforcing.

I have only (so far) tested on a Pixel 5a and Pixel 6.
Stock Google rooted with Magisk canary and a few modules installed.
Denylist is not enforced.

I have had 'gms' added to the list for a few weeks for testing and have no issues.

Pixel 6 has no modules that source the DenyList.
_Busybox, MagiskHide Props Config, Nano, Systemless Debloater, Systemless Hosts, Universal SaftyNet Fix (Test), Zip Binary._

Pixel 5a
Same modules as the 6 with one addition.
Shamiko is a 'Zygisk' module that uses the DenyList.
_I see no difference if 'gms' is included or not with Shamiko._


> For example, if someone adds Play Services to the DenyList but doesn't enable "Enforce DenyList" until later, this will miss it and the module won't work for them until they reboot.

Originally, the current command would error out when not enforcing.
Now that _Allow modifying denylist without enforcement_ was added, the command runs when not enforcing.


Even the current script will require a reboot to run again if someone decides to enable "Enforce DenyList" and then add Play Services to the list.

2022-03-04 03:49 UTC, HuskyDG commented
What do you mean when you add gms to Denylist? SafetyNet Fix already let you pass SafetyNet???

2022-03-05 03:24 UTC, ipdev99 commented
> What do you mean when you add gms to Denylist? SafetyNet Fix already let you pass SafetyNet???

SafetyNet Fix allows you to pass SafetyNet by tricking SafetyNet into thinking you have a device that does not support _hardware attestation_.
The SafetyNet check will fall back to the _basic_ test and we can hide sensitive [secure] setting from the basic test.

When Magisk's Denylist is enforced, Magisk will unload (disabled) itself while processes on the Denylist are called.

SafetyNet uses `com.google.android.gms.unstable` and (sometimes) the main process `com.google.android.gms`.

If the processes are on the Denylist when it is enforced, this module will be disabled while SafetyNet is checked.
_You will fail SafetyNet the same as if you did not have Magisk or this module installed._

This is why _gms_ needs to be removed from the Denylist when it is _enforced_.

2022-03-05 03:26 UTC, HuskyDG commented
> > What do you mean when you add gms to Denylist? SafetyNet Fix already let you pass SafetyNet???
> 
> SafetyNet Fix allows you to pass SafetyNet by tricking SafetyNet into thinking you have a device that does not support _hardware attestation_. The SafetyNet check will fall back to the _basic_ test and we can hide sensitive [secure] setting from the basic test.
> 
> When Magisk's Denylist is enforced, Magisk will unload (disabled) itself while processes on the Denylist are called.
> 
> SafetyNet uses `com.google.android.gms.unstable` and (sometimes) the main process `com.google.android.gms`.
> 
> If the processes are on the Denylist when it is enforced, this module will be disabled while SafetyNet is checked. _You will fail SafetyNet the same as if you did not have Magisk or this module installed._
> 
> This is why _gms_ needs to be removed from the Denylist when it is _enforced_.

**PLEASE READ MY QUESTION AGAIN**

2022-03-05 03:33 UTC, HuskyDG commented
Since you could pass SafetyNet with USNF, you don't need to apply Shamiko for gms

2022-03-05 04:01 UTC, ipdev99 commented
> > > What do you mean when you add gms to Denylist? SafetyNet Fix already let you pass SafetyNet???
> > 
> > 
> > SafetyNet Fix allows you to pass SafetyNet by tricking SafetyNet into thinking you have a device that does not support _hardware attestation_. The SafetyNet check will fall back to the _basic_ test and we can hide sensitive [secure] setting from the basic test.
> > When Magisk's Denylist is enforced, Magisk will unload (disabled) itself while processes on the Denylist are called.
> > SafetyNet uses `com.google.android.gms.unstable` and (sometimes) the main process `com.google.android.gms`.
> > If the processes are on the Denylist when it is enforced, this module will be disabled while SafetyNet is checked. _You will fail SafetyNet the same as if you did not have Magisk or this module installed._
> > This is why _gms_ needs to be removed from the Denylist when it is _enforced_.
> 
> You were telling what i already knew :))
> 
> but **PLEASE READ MY QUESTION AGAIN**
> 
> I asked why did you want to add gms into denylist if Denylist was not enforced.

Save for testing, I have no need at the moment to include gms in the Denylist.
I include part or all of gms to the Denylist when not enforcing for testing only.

Some modules and apps for advanced hiding source the Denylist.

Currently I do not know of one that requires, includes or utilizes gms.
This does not mean there is not or will not be one.

Since there is no need or reason to remove gms from the Denylist when not enforcing, why remove it?
_Use a scalpel instead of a machete._

2022-03-09 05:34 UTC, HuskyDG commented
> > > > What do you mean when you add gms to Denylist? SafetyNet Fix already let you pass SafetyNet???
> > > 
> > > 
> > > SafetyNet Fix allows you to pass SafetyNet by tricking SafetyNet into thinking you have a device that does not support _hardware attestation_. The SafetyNet check will fall back to the _basic_ test and we can hide sensitive [secure] setting from the basic test.
> > > When Magisk's Denylist is enforced, Magisk will unload (disabled) itself while processes on the Denylist are called.
> > > SafetyNet uses `com.google.android.gms.unstable` and (sometimes) the main process `com.google.android.gms`.
> > > If the processes are on the Denylist when it is enforced, this module will be disabled while SafetyNet is checked. _You will fail SafetyNet the same as if you did not have Magisk or this module installed._
> > > This is why _gms_ needs to be removed from the Denylist when it is _enforced_.
> > 
> > 
> > You were telling what i already knew :))
> > but **PLEASE READ MY QUESTION AGAIN**
> > I asked why did you want to add gms into denylist if Denylist was not enforced.
> 
> Save for testing, I have no need at the moment to include gms in the Denylist. I include part or all of gms to the Denylist when not enforcing for testing only.
> 
> Some modules and apps for advanced hiding source the Denylist.
> 
> Currently I do not know of one that requires, includes or utilizes gms. This does not mean there is not or will not be one.
> 
> Since there is no need or reason to remove gms from the Denylist when not enforcing, why remove it? _Use a scalpel instead of a machete._

It seems only Shamiko read denylist now.

2022-03-11 01:33 UTC, kdrag0n commented
> Originally, the current command would error out when not enforcing. Now that _[Allow modifying denylist without enforcement](https://github.com/topjohnwu/Magisk/commit/76ddfeb93a8b3612cd68988323f422e996751e16)_ was added, the command runs when not enforcing.

Nice catch, I didn't realize it used to ignore the command when not enforcing DenyList. Thanks for clarifying.

2022-03-11 01:33 UTC, kdrag0n approved these changes

2022-03-11 01:33 UTC, merged